# Generated by Django 5.2.3 on 2025-06-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_name', models.CharField(max_length=100, verbose_name='Academic Year Name')),
                ('academic_year_start_date', models.DateField(verbose_name='Academic Year Start Date')),
                ('academic_year_end_date', models.DateField(verbose_name='Academic Year End Date')),
                ('academic_year_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100, verbose_name='Academic Year Status')),
            ],
            options={
                'verbose_name': 'academic year',
                'verbose_name_plural': 'academic years',
                'db_table': 'academic_years',
                'ordering': ['-academic_year_name'],
                'indexes': [models.Index(fields=['academic_year_name'], name='academic_ye_academi_6a686a_idx')],
                'unique_together': {('academic_year_name', 'academic_year_start_date', 'academic_year_end_date')},
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='School Full Name')),
                ('school_type', models.CharField(choices=[('PUBLIC', 'A Public School'), ('PRIVATE', 'A Private School')], default='PUBLIC', max_length=10, verbose_name='School Type')),
                ('address', models.CharField(max_length=100, verbose_name='School Address')),
                ('city', models.CharField(max_length=100, verbose_name='School City')),
                ('state', models.CharField(max_length=100, verbose_name='School State')),
                ('zip_code', models.CharField(max_length=10, verbose_name='School Zip Code')),
                ('phone', models.CharField(max_length=10, verbose_name='School Phone')),
                ('website', models.URLField(max_length=100, verbose_name='School Website')),
                ('principal', models.CharField(max_length=100, verbose_name='School Principal Name')),
                ('established_date', models.DateField(verbose_name='School Established Date')),
            ],
            options={
                'verbose_name': 'school',
                'verbose_name_plural': 'school',
                'ordering': ['-full_name'],
                'indexes': [models.Index(fields=['full_name'], name='school_scho_full_na_90b7b9_idx')],
            },
        ),
    ]
