# Generated by Django 5.2.3 on 2025-06-19 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classdetail', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fee Name')),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fee Amount')),
                ('fee_date', models.DateField(blank=True, null=True, verbose_name='Fee Date')),
                ('fee_status', models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=100, null=True, verbose_name='Fee Status')),
                ('fee_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fee Description')),
                ('fee_payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=100, null=True, verbose_name='Fee Payment Method')),
                ('fee_payment_date', models.DateField(blank=True, null=True, verbose_name='Fee Payment Date')),
                ('fee_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fee Payment Amount')),
                ('fee_payment_status', models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=100, null=True, verbose_name='Fee Payment Status')),
                ('fee_payment_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fee Payment Description')),
                ('fee_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classdetail.classdetail', verbose_name='Fee Class')),
                ('fee_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Fee Student')),
            ],
            options={
                'verbose_name': 'fee',
                'verbose_name_plural': 'fees',
                'db_table': 'fees',
                'ordering': ['fee_name'],
                'indexes': [models.Index(fields=['fee_name'], name='fees_fee_nam_567e13_idx')],
            },
        ),
    ]
