# Generated by Django 4.2.23 on 2025-06-19 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('teachers', '0001_initial'),
        ('subjects', '0001_initial'),
        ('classdetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Material Title')),
                ('category', models.CharField(choices=[('SLIDE', 'Chapter Slide'), ('TEXT_BOOK', 'A text book'), ('REFERENCE_BOOK', 'A reference book'), ('OLD_QUESTION', 'Previous board exam question'), ('AUDIO_BOOK', 'An audio book')], max_length=30, verbose_name='Category')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Material Description')),
                ('material_file', models.FileField(upload_to='material/', verbose_name='Select file')),
                ('upload_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Upload Date')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear', verbose_name='Academic Year')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classdetail.classdetail', verbose_name='Class Name')),
                ('material_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Material Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
                'ordering': ['-title'],
            },
        ),
    ]
