# Generated by Django 5.2.3 on 2025-06-19 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classdetail', '0001_initial'),
        ('school', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Term Name')),
                ('term_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Term Description')),
                ('term_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100, null=True, verbose_name='Term Status')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Exam Date')),
                ('exam_time', models.TimeField(blank=True, null=True, verbose_name='Exam Time')),
                ('exam_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Exam Level')),
                ('exam_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=100, null=True, verbose_name='Exam Status')),
                ('exam_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.academicyear', verbose_name='Exam Academic Year')),
                ('exam_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classdetail.classdetail', verbose_name='Exam Class')),
                ('exam_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Exam Subject')),
                ('exam_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.term', verbose_name='Exam Term')),
            ],
            options={
                'verbose_name': 'exam',
                'verbose_name_plural': 'exams',
                'db_table': 'exams',
                'ordering': ['exam_term'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_marks', models.FloatField(blank=True, null=True, verbose_name='Full Marks')),
                ('pass_marks', models.FloatField(blank=True, null=True, verbose_name='Pass Marks')),
                ('theory_marks', models.FloatField(blank=True, null=True, verbose_name='Theory Marks')),
                ('practical_marks', models.FloatField(blank=True, null=True, verbose_name='Practical Marks')),
                ('credit_hours', models.FloatField(blank=True, null=True, verbose_name='Credit Hours')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='Exam')),
                ('exam_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Exam Subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.FloatField(blank=True, null=True, verbose_name='Obtained Marks')),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D+', 'D+'), ('D', 'D'), ('E', 'E')], max_length=25, null=True, verbose_name='Grade')),
                ('grade_point', models.FloatField(blank=True, null=True, verbose_name='Grade Point')),
                ('weighted_grade', models.FloatField(blank=True, null=True, verbose_name='Weighted Grade')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('exam_ledger_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=100, null=True, verbose_name='Exam Ledger Status')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.examsubject', verbose_name='Exam')),
            ],
            options={
                'verbose_name': 'exam_ledger',
                'verbose_name_plural': 'exam_ledgers',
                'db_table': 'exam_ledgers',
                'ordering': ['student'],
                'indexes': [models.Index(fields=['student'], name='exam_ledger_student_5f5c37_idx')],
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_term'], name='exams_exam_te_1115c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('exam_term', 'exam_date', 'exam_time', 'exam_subject', 'exam_class', 'exam_level', 'exam_status', 'exam_academic_year')},
        ),
    ]
