# Generated by Django 5.2.3 on 2025-06-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Name')),
                ('book_author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Author')),
                ('book_publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Publisher')),
                ('book_publication_date', models.DateField(blank=True, null=True, verbose_name='Book Publication Date')),
                ('book_isbn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book ISBN')),
                ('book_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Category')),
                ('book_quantity', models.IntegerField(blank=True, null=True, verbose_name='Book Quantity')),
                ('book_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Book Price')),
                ('book_description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Book Description')),
                ('book_status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('lost', 'Lost')], max_length=100)),
                ('book_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Location')),
                ('book_shelf', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Shelf')),
                ('book_row', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Row')),
                ('book_column', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Column')),
                ('book_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Level')),
                ('book_section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Section')),
                ('book_sub_section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Sub Section')),
                ('book_rack_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Rack Number')),
                ('book_row_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Row Number')),
                ('book_column_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Column Number')),
                ('book_level_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Book Level Number')),
            ],
            options={
                'verbose_name': 'library',
                'verbose_name_plural': 'libraries',
                'db_table': 'library',
                'ordering': ['book_name'],
                'indexes': [models.Index(fields=['book_name'], name='library_book_na_d7b6cc_idx')],
            },
        ),
    ]
