# Generated by Django 4.2.23 on 2025-06-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('teachers', '0001_initial'),
        ('subjects', '0001_initial'),
        ('classdetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Assignment Title')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('question_file', models.FileField(blank=True, null=True, upload_to='assignments/questions/', verbose_name='Select Assignment File')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Assignment Question')),
                ('remark', models.CharField(max_length=100, verbose_name='Assignment Details')),
                ('full_mark', models.FloatField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear', verbose_name='Academic Year')),
                ('assignment_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Assignment Subject')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classdetail.classdetail', verbose_name='Class Name')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'ordering': ['-title'],
            },
        ),
    ]
