# Generated by Django 5.2.3 on 2025-06-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teacher Name')),
                ('teacher_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Teacher Email')),
                ('teacher_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teacher Phone')),
                ('teacher_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teacher Address')),
                ('teacher_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=100, null=True, verbose_name='Teacher Gender')),
                ('academic_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Academic Level')),
                ('teacher_date_of_birth', models.DateField(blank=True, null=True, verbose_name='Teacher Date of Birth')),
                ('teacher_date_of_joining', models.DateField(blank=True, null=True, verbose_name='Teacher Date of Joining')),
                ('teacher_date_of_leaving', models.DateField(blank=True, null=True, verbose_name='Teacher Date of Leaving')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'db_table': 'teachers',
                'ordering': ['teacher_name'],
                'indexes': [models.Index(fields=['teacher_name'], name='teachers_teacher_0d67d6_idx')],
                'unique_together': {('teacher_name', 'teacher_email', 'teacher_phone', 'teacher_address', 'teacher_gender', 'teacher_date_of_birth', 'teacher_date_of_joining', 'teacher_date_of_leaving')},
            },
        ),
    ]
