# Generated by Django 5.2.3 on 2025-06-19 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classdetail', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject Name')),
                ('subject_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject Code')),
                ('subject_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject Description')),
                ('subject_type', models.CharField(blank=True, choices=[('theory', 'Theory'), ('practical', 'Practical')], max_length=100, null=True, verbose_name='Subject Type')),
                ('credit_hours', models.FloatField(blank=True, null=True, verbose_name='Credit Hours')),
                ('subject_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100, null=True, verbose_name='Subject Status')),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classdetail.classdetail', verbose_name='Class Name')),
                ('subject_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Subject Teacher')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'db_table': 'subjects',
                'ordering': ['subject_name'],
                'indexes': [models.Index(fields=['subject_name'], name='subjects_subject_11cceb_idx')],
                'unique_together': {('subject_name', 'subject_code', 'subject_description', 'class_name', 'subject_teacher', 'subject_type', 'credit_hours', 'subject_status')},
            },
        ),
    ]
