# Generated by Django 5.2.3 on 2025-06-19 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Class Name')),
                ('class_type', models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('higher_secondary', 'Higher Secondary')], max_length=100, null=True, verbose_name='Class Type')),
                ('class_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100, null=True, verbose_name='Class Status')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Class Teacher')),
            ],
            options={
                'verbose_name': 'classdetail',
                'verbose_name_plural': 'classdetails',
                'db_table': 'class_details',
                'ordering': ['class_name'],
                'indexes': [models.Index(fields=['class_name'], name='class_detai_class_n_9078e0_idx')],
                'unique_together': {('class_name', 'class_teacher', 'class_type', 'class_status')},
            },
        ),
    ]
